import type { AchievementDef } from './achievement.types'

export const ACHIEVEMENT_DEFS: AchievementDef[] = [
  // ── Performance ─────────────────────────────────────────────────────────
  {
    id: 'goat_week',
    name: 'GOAT Week',
    description: 'Highest single-week score in league history',
    icon: '🐐',
    rarity: 'legendary',
    category: 'performance',
  },
  {
    id: 'double_century',
    name: 'Double Century',
    description: 'Scored 200+ points in a single week',
    icon: '💯',
    rarity: 'epic',
    category: 'performance',
  },
  {
    id: 'century_club',
    name: 'Century Club',
    description: 'Scored 150+ points in a single week',
    icon: '💫',
    rarity: 'rare',
    category: 'performance',
  },
  {
    id: 'zero_hero',
    name: 'Zero Hero',
    description: 'A starter scored exactly 0 fantasy points',
    icon: '🦗',
    rarity: 'common',
    category: 'performance',
  },
  // ── Season ──────────────────────────────────────────────────────────────
  {
    id: 'champion',
    name: 'Champion',
    description: 'Won the championship',
    icon: '🏆',
    rarity: 'legendary',
    category: 'season',
  },
  {
    id: 'runner_up',
    name: 'Runner-Up',
    description: 'Finished 2nd in the championship',
    icon: '🥈',
    rarity: 'epic',
    category: 'season',
  },
  {
    id: 'playoff_berth',
    name: 'Playoff Bound',
    description: 'Made the playoffs',
    icon: '🎯',
    rarity: 'common',
    category: 'season',
  },
  {
    id: 'dominant_season',
    name: 'Dominant',
    description: 'Finished the regular season with 10+ wins',
    icon: '👑',
    rarity: 'legendary',
    category: 'season',
  },
  {
    id: 'toilet_bowl',
    name: 'Toilet Bowl Champ',
    description: 'Won the consolation bracket',
    icon: '🚽',
    rarity: 'common',
    category: 'season',
  },
  {
    id: 'last_place',
    name: 'Last Place',
    description: 'Finished dead last in the standings',
    icon: '💀',
    rarity: 'common',
    category: 'season',
  },
  {
    id: 'hot_start',
    name: 'Hot Start',
    description: 'Won the first 4 weeks of the season',
    icon: '🔥',
    rarity: 'rare',
    category: 'season',
  },
  {
    id: 'redemption_arc',
    name: 'Redemption Arc',
    description: 'Made the playoffs after starting 0-3 or worse',
    icon: '🔄',
    rarity: 'epic',
    category: 'season',
  },
  // ── Scoring ─────────────────────────────────────────────────────────────
  {
    id: 'blowout_king',
    name: 'Blowout King',
    description: 'Won by 50+ points in a single game',
    icon: '💥',
    rarity: 'rare',
    category: 'scoring',
  },
  {
    id: 'massacre',
    name: 'The Massacre',
    description: 'Largest single-game margin in league history',
    icon: '⚔️',
    rarity: 'legendary',
    category: 'scoring',
  },
  {
    id: 'nail_biter',
    name: 'Nail Biter',
    description: 'Won by fewer than 5 points',
    icon: '😬',
    rarity: 'common',
    category: 'scoring',
  },
  {
    id: 'heartbreak',
    name: 'Heartbreak',
    description: 'Lost by fewer than 2 points',
    icon: '💔',
    rarity: 'common',
    category: 'scoring',
  },
  {
    id: 'lucky_win',
    name: 'Lucky Duck',
    description: 'Won despite scoring below the weekly league average',
    icon: '🍀',
    rarity: 'rare',
    category: 'scoring',
  },
  {
    id: 'unlucky_loss',
    name: 'Robbed',
    description: 'Lost despite scoring above the weekly league average',
    icon: '😤',
    rarity: 'rare',
    category: 'scoring',
  },
  {
    id: 'highest_scorer',
    name: 'Top Gun',
    description: 'Led the league in total points for the season',
    icon: '🎖️',
    rarity: 'legendary',
    category: 'scoring',
  },
  // ── GM Activity ─────────────────────────────────────────────────────────
  {
    id: 'waiver_wolf',
    name: 'Waiver Wolf',
    description: 'Most waiver/FA claims in a season',
    icon: '🐺',
    rarity: 'rare',
    category: 'gm',
  },
  {
    id: 'trade_machine',
    name: 'Trade Machine',
    description: 'Completed 3+ trades in a season',
    icon: '🤝',
    rarity: 'rare',
    category: 'gm',
  },
  {
    id: 'hodler',
    name: 'Diamond Hands',
    description: 'Fewest roster moves in a season',
    icon: '💎',
    rarity: 'common',
    category: 'gm',
  },
  {
    id: 'big_spender',
    name: 'Big Spender',
    description: 'Spent 90%+ of FAAB budget',
    icon: '💸',
    rarity: 'common',
    category: 'gm',
  },
  // ── Rivalry ─────────────────────────────────────────────────────────────
  {
    id: 'nemesis',
    name: 'Nemesis',
    description: 'Lost to the same opponent 3+ times',
    icon: '👿',
    rarity: 'common',
    category: 'rivalry',
  },
  {
    id: 'bully',
    name: 'The Bully',
    description: 'Beat the same opponent 3+ times',
    icon: '😈',
    rarity: 'rare',
    category: 'rivalry',
  },
]

export const ACHIEVEMENT_MAP = Object.fromEntries(ACHIEVEMENT_DEFS.map((a) => [a.id, a])) as Record<
  string,
  AchievementDef
>
